name: Windows VS Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest
    
    steps:
      - name: Setup Visual Studio tools
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'

      - name: Setup Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Display Visual Studio info
        shell: cmd
        run: |
          cl 2>&1 | findstr /C:"Version"
          echo MSBuild version:
          msbuild -version
      
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11' 
      
      - name: Checkout Xerces-C
        uses: actions/checkout@v4
        with:
          repository: apache/xerces-c
          ref: v3.3.0
          path: xerces-c-source

      - name: Checkout Geant4
        uses: actions/checkout@v4
        with:
          repository: Geant4/geant4
          ref: v11.4.0
          path: geant4-source
      
      - name: Checkout Geant4 Pybind
        uses: actions/checkout@v4
        with:
          repository: HaarigerHarald/geant4_pybind
          ref: v0.1.2
          path: geant4-pybind-source
          submodules: recursive
      
      - name: Build Xerces-C
        shell: cmd
        run: |
          mkdir xerces-c-build
          cd xerces-c-build
          cmake "..\xerces-c-source" ^
            -DCMAKE_INSTALL_PREFIX="..\install" ^
            -DCMAKE_CXX_FLAGS_RELEASE="/MP4" ^
            -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded ^
            -DBUILD_SHARED_LIBS=OFF
          cmake --build . --config Release
          cmake --install .
          cd ..\
      
      - name: Build Gent4
        shell: cmd
        run: |
          mkdir geant4-build
          cd geant4-build
          cmake "..\geant4-source" ^
            -DCMAKE_INSTALL_PREFIX="..\install" ^
            -DBUILD_STATIC_LIBS=ON ^
            -DBUILD_SHARED_LIBS=OFF ^
            -DGEANT4_INSTALL_EXAMPLES=OFF ^
            -DGEANT4_BUILD_MSVC_MP=ON ^
            -DCMAKE_CXX_FLAGS_RELEASE="/MP4" ^
            -DGEANT4_USE_OPENGL_WIN32=ON ^
            -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded ^
            -DGEANT4_USE_GDML=ON
          cmake --build . --config Release --target install
          cd ..\
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: install
          path: ./install
      
      - name: Build Gent4 Pybind
        env:
          CMAKE_ARGS: >-
            -DCMAKE_PREFIX_PATH=${{ github.workspace }}\install
            -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
        shell: cmd
        run: |
          call .\install\bin\geant4.bat
          pip wheel .\geant4-pybind-source -w .\wheelhouse
      
      - name: Upload Wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: ./wheelhouse
